const planData = {
  id: 1,
  type: "back",
  workout: "바벨로우",
  totalSet: 10,
  maxWeight: {
    weight: 100,
    count: 1,
  },
  createdAt: "9시 30분",
  condition: ["화남", "피곤함", "우울함", "신남"],
  comment: "아 진짜 개빡치네 너무 아쉽게 못 들었음",
}

export const equipmentData: string[] = [
  "바벨",
  "덤벨",
  "머신",
  "스미스",
  "케이블",
  "맨몸",
]

export const workoutData: Record<
  "back" | "chest" | "shoulder" | "leg" | "arm",
  string[]
> = {
  back: [
    "데드리프트",
    "로우",
    "풀업",
    "친업",
    "랫풀다운",
    "암풀다운",
    "컨벤셔널데드",
    "루마니안데드",
    "렉풀",
    "티바로우",
    "하이로우",
    "로우로우",
    "원암로우",
    "벤트오버로우",
    "펜들레이로우",
    "시티드로우",
    "프론트로우",
    "슈러그",
  ],
  chest: [
    "벤치프레스",
    "인클라인프레스",
    "디클라인프레스",
    "체스트프레스",
    "클로즈그립프레스",
    "와이드프레스",
    "시티드프레스",
    "플랫프레스",
    "팩덱플라이",
    "플라이",
    "딥스",
    "풀오버",
  ],
  shoulder: [
    "오버헤드프레스",
    "밀리터리프레스",
    "숄더프레스",
    "푸쉬프레스",
    "비하인드넥프레스",
    "프론트레이즈",
    "사이드레터럴레이즈",
    "벤트오버레이즈",
    "업라이트로우",
    "페이스풀",
  ],
  leg: [
    "스쿼트",
    "백스쿼트",
    "핵스쿼트",
    "브이스쿼트",
    "레그프레스",
    "레그익스텐션",
    "레그컬",
    "런지",
    "스티프데드",
    "스모데드",
    "인어싸이",
    "아웃싸이",
    "프론트스쿼트",
    "스플릿스쿼트",
    "와이드스쿼트",
    "펜듈럼스쿼트",
    "힙쓰러스트",
    "카프레이즈",
  ],
  arm: [
    "컬",
    "해머컬",
    "푸쉬다운",
    "스컬크러셔",
    "삼두익스텐션",
    "리버스컬",
    "리스트컬",
    "프리쳐컬",
    "스파이더컬",
    "리버스리스트컬",
    "컨센트레이션컬",
  ],
}

export const workoutData2: {
  [key: string]: any
} = {
  back: {
    babel: [
      "로우",
      "벤트오버로우",
      "펜들레이로우",
      "컨벤셔널데드리프트",
      "루마니안데드리프트",
      "슈러그",
      "티바로우",
      "렉풀",
    ],
    dumbbell: ["원암로우", "로우로우", "슈러그", "투암로우", "데드리프트"],
    smith: ["로우", "루마니안데드리프트", "슈러그", "렉풀"],
    machine: [
      "로우로우",
      "하이로우",
      "랫풀다운",
      "티바로우",
      "시티드로우",
      "풀업",
      "프론트로우",
      "벤트오버로우",
      "아이솔레이트로우",
      "암풀다운",
      "친업",
    ],
    cable: [
      "로우로우",
      "하이로우",
      "랫풀다운",
      "티바로우",
      "시티드로우",
      "암풀다운",
    ],
  },
  chest: {
    babel: [
      "벤치프레스",
      "디클라인프레스",
      "인클라인프레스",
      "클로즈그립프레스",
      "풀오버",
    ],
    dumbbell: [
      "벤치프레스",
      "디클라인프레스",
      "인클라인프레스",
      "클로즈그립프레스",
      "풀오버",
      "플라이",
    ],
    smith: [
      "벤치프레스",
      "디클라인프레스",
      "인클라인프레스",
      "클로즈그립프레스",
    ],
    machine: [
      "펙덱플라이",
      "딥스",
      "체스트프레스",
      "시티드프레스",
      "인클라인프레스",
      "디클라인프레스",
      "와이드프레스",
      "플랫프레스",
    ],
    cable: [
      "플라이",
      "체스트프레스",
      "시티드프레스",
      "와이드프레스",
      "인클라인프레스",
      "디클라인프레스",
    ],
  },
  shoulder: {
    babel: [
      "오버헤드프레스",
      "밀리터리프레스",
      "사이드레터럴레이즈",
      "프론트레이즈",
      "비하인드넥프레스",
      "푸쉬프레스",
    ],
    dumbbell: [
      "숄더프레스",
      "사이드레터럴레이즈",
      "프론트레이즈",
      "벤트오버레이즈",
      "업라이트로우",
      "푸쉬프레스",
    ],
    smith: [
      "오버헤드프레스",
      "밀리터리프레스",
      "사이드레터럴레이즈",
      "프론트레이즈",
      "비하인드넥프레스",
    ],
    machine: [
      "숄더프레스",
      "사이드레터럴레이즈",
      "프론트레이즈",
      "벤트오버레이즈",
      "업라이트로우",
    ],
    cable: [
      "숄더프레스",
      "사이드레터럴레이즈",
      "프론트레이즈",
      "벤트오버레이즈",
      "업라이트로우",
      "페이스풀",
    ],
  },
  leg: {
    babel: [
      "스쿼트",
      "하이바스쿼트",
      "로우바스쿼트",
      "프론트스쿼트",
      "스플릿스쿼트",
      "런지",
      "힙쓰러스트",
      "와이드스쿼트",
      "스모데드리프트",
      "스티프데드리프트",
    ],
    dumbbell: [
      "스쿼트",
      "하이바스쿼트",
      "로우바스쿼트",
      "프론트스쿼트",
      "스플릿스쿼트",
      "런지",
      "힙쓰러스트",
      "와이드스쿼트",
      "스모데드리프트",
      "스티프데드리프트",
    ],
    smith: [
      "스쿼트",
      "하이바스쿼트",
      "로우바스쿼트",
      "프론트스쿼트",
      "스플릿스쿼트",
      "런지",
      "힙쓰러스트",
      "와이드스쿼트",
      "스모데드리프트",
      "스티프데드리프트",
    ],
    machine: [
      "숄더프레스",
      "사이드레터럴레이즈",
      "프론트레이즈",
      "벤트오버레이즈",
      "업라이트로우",
    ],
    cable: [
      "숄더프레스",
      "사이드레터럴레이즈",
      "프론트레이즈",
      "벤트오버레이즈",
      "업라이트로우",
      "페이스풀",
    ],
  },
  arm: [
    "해머컬",
    "바벨컬",
    "덤벨컬",
    "케이블컬",
    "리버스컬",
    "리스트컬",
    "리버스리스트컬",
  ],
}

export const setData = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]
export const setTypeData = ["웜업", "본 세트", "PR", "연습"]
export const countData = [
  "1 + α",
  "2 + α",
  "3 + α",
  "4 + α",
  "5 + α",
  "6 + α",
  "7 + α",
  "8 + α",
  "9 + α",
  "10 + α",
  "11 + α",
  "12 + α",
  "13 + α",
  "14 + α",
  "15 + α",
]

export const conditionData = [
  {
    id: 1,
    condition: "좋음",
  },
  {
    id: 2,
    condition: "피곤함",
  },
  {
    id: 3,
    condition: "화남",
  },
  {
    id: 4,
    condition: "아픔",
  },
  {
    id: 5,
    condition: "슬픔",
  },
  {
    id: 6,
    condition: "신남",
  },
  {
    id: 7,
    condition: "상쾌함",
  },
  {
    id: 8,
    condition: "양호함",
  },
  {
    id: 9,
    condition: "짜증남",
  },
]

export const mockupData = [
  {
    condition: ["화남", "피곤함", "좋음"],
    content: "Asdasdasd",
    createdAt: "2025.03.14 06:58:34",
    equipment: "덤벨",
    id: 9,
    setWithCount: [],
    title: "",
    type: "chest",
    updatedAt: "2024.11.14 06:58:34",
    weight: "60",
    workout: "체스트프레스",
  },
  {
    condition: ["화남", "피곤함", "좋음"],
    content: "Asdasdasd",
    createdAt: "2025.02.14 06:58:34",
    equipment: "덤벨",
    id: 9,
    setWithCount: [],
    title: "",
    type: "chest",
    updatedAt: "2024.11.14 06:58:34",
    weight: "60",
    workout: "체스트프레스",
  },
  {
    condition: ["화남", "피곤함", "좋음"],
    content: "Asdasdasd",
    createdAt: "2025.01.14 06:58:34",
    equipment: "덤벨",
    id: 8,
    setWithCount: [],
    title: "",
    type: "chest",
    updatedAt: "2024.11.14 06:58:34",
    weight: "60",
    workout: "체스트프레스",
  },
  {
    condition: ["화남", "피곤함", "좋음"],
    content: "Asdasdasd",
    createdAt: "2024.12.14 06:58:34",
    equipment: "덤벨",
    id: 7,
    setWithCount: [],
    title: "",
    type: "chest",
    updatedAt: "2024.11.14 06:58:34",
    weight: "60",
    workout: "체스트프레스",
  },
  {
    condition: ["화남", "피곤함", "좋음"],
    content: "Asdasdasd",
    createdAt: "2024.11.14 06:58:34",
    equipment: "덤벨",
    id: 6,
    setWithCount: [],
    title: "",
    type: "chest",
    updatedAt: "2024.11.14 06:58:34",
    weight: "60",
    workout: "체스트프레스",
  },
  {
    condition: [],
    content: "",
    createdAt: "2023.12.14 06:31:35",
    equipment: "덤벨",
    id: 5,
    setWithCount: [],
    title: "",
    type: "shoulder",
    updatedAt: "2024.12.14 06:31:35",
    weight: "60",
    workout: "비하인드넥프레스",
  },
  {
    condition: ["좋음", "피곤함", "화남", "슬픔"],
    content: "화이팅!!!",
    createdAt: "2023.11.10 03:42:17",
    equipment: "바벨",
    id: 4,
    setWithCount: [],
    title: "",
    type: "leg",
    updatedAt: "2024.11.08 03:42:17",
    weight: "100",
    workout: "레그프레스",
  },
  {
    condition: ["좋음", "피곤함", "화남", "아픔"],
    content: "열심히 운동합시다 화이팅!!!",
    createdAt: "2023.11.10 03:41:38",
    equipment: "스미스",
    id: 3,
    setWithCount: [],
    title: "오늘도 열심히",
    type: "shoulder",
    updatedAt: "2024.11.08 03:41:38",
    weight: "80",
    workout: "오버헤드프레스",
  },
  {
    condition: ["좋음", "피곤함", "화남", "아픔"],
    content: "",
    createdAt: "2023.10.08 03:40:49",
    equipment: "덤벨",
    id: 2,
    setWithCount: [],
    title: "",
    type: "chest",
    updatedAt: "2024.10.08 03:40:49",
    weight: "70",
    workout: "클로즈그립프레스",
  },
  {
    condition: [],
    content: "",
    createdAt: "2023.10.07 03:40:35",
    equipment: "바벨",
    id: 1,
    setWithCount: [],
    title: "",
    type: "back",
    updatedAt: "2024.11.08 03:40:35",
    weight: "60",
    workout: "데드리프트",
  },
]
